const ENGLISH_DATA = {
    pronouns: [
        { type: "Sujet", en: "I", fr: "Je", example: "I am a student.", translation: "Je suis un étudiant." },
        { type: "Sujet", en: "You", fr: "Tu / Vous", example: "You like apples.", translation: "Tu aimes les pommes." },
        { type: "Sujet", en: "He", fr: "Il", example: "He plays football.", translation: "Il joue au football." },
        { type: "Sujet", en: "She", fr: "Elle", example: "She speaks English.", translation: "Elle parle anglais." },
        { type: "Sujet", en: "It", fr: "Il / Elle (objet)", example: "It is a big house.", translation: "C'est une grande maison." },
        { type: "Sujet", en: "We", fr: "Nous", example: "We go to school.", translation: "Nous allons à l'école." },
        { type: "Sujet", en: "They", fr: "Ils / Elles", example: "They watch TV.", translation: "Ils regardent la télé." },
        { type: "Objet", en: "Me", fr: "Moi / Me", example: "He calls me.", translation: "Il m'appelle." },
        { type: "Objet", en: "You", fr: "Toi / Te", example: "I see you.", translation: "Je te vois." },
        { type: "Objet", en: "Him", fr: "Lui / Le", example: "Listen to him.", translation: "Écoute-le." },
        { type: "Objet", en: "Her", fr: "Elle / La", example: "Give it to her.", translation: "Donne-le lui (à elle)." },
        { type: "Possessif (Adj)", en: "My", fr: "Mon / Ma / Mes", example: "This is my dog.", translation: "C'est mon chien." },
        { type: "Possessif (Adj)", en: "Your", fr: "Ton / Ta / Tes", example: "Where is your car?", translation: "Où est ta voiture ?" },
        { type: "Possessif (Pro)", en: "Mine", fr: "Le mien / La mienne", example: "This book is mine.", translation: "Ce livre est le mien." },
        { type: "Réfléchi", en: "Myself", fr: "Moi-même", example: "I did it myself.", translation: "Je l'ai fait moi-même." }
    ],

    adjectives: [
        { en: "Happy", fr: "Heureux", category: "Émotion" },
        { en: "Sad", fr: "Triste", category: "Émotion" },
        { en: "Big", fr: "Grand", category: "Taille" },
        { en: "Small", fr: "Petit", category: "Taille" },
        { en: "Fast", fr: "Rapide", category: "Vitesse" },
        { en: "Slow", fr: "Lent", category: "Vitesse" },
        { en: "Tall", fr: "Grand (taille)", category: "Taille" },
        { en: "Short", fr: "Court / Petit", category: "Taille" },
        { en: "Hot", fr: "Chaud", category: "Météo" },
        { en: "Cold", fr: "Froid", category: "Météo" },
        { en: "Young", fr: "Jeune", category: "Âge" },
        { en: "Old", fr: "Vieux", category: "Âge" },
        { en: "Beautiful", fr: "Beau / Belle", category: "Apparence" },
        { en: "Ugly", fr: "Laid", category: "Apparence" },
        { en: "Rich", fr: "Riche", category: "Statut" },
        { en: "Poor", fr: "Pauvre", category: "Statut" },
        { en: "Strong", fr: "Fort", category: "Qualité" },
        { en: "Weak", fr: "Faible", category: "Qualité" },
        { en: "Hard", fr: "Dur / Difficile", category: "Qualité" },
        { en: "Easy", fr: "Facile", category: "Qualité" },
        { en: "Red", fr: "Rouge", category: "Couleur" },
        { en: "Blue", fr: "Bleu", category: "Couleur" },
        { en: "Green", fr: "Vert", category: "Couleur" },
        { en: "Yellow", fr: "Jaune", category: "Couleur" },
        { en: "Black", fr: "Noir", category: "Couleur" },
        { en: "White", fr: "Blanc", category: "Couleur" },
        { en: "French", fr: "Français", category: "Nationalité" },
        { en: "English", fr: "Anglais", category: "Nationalité" },
        { en: "American", fr: "Américain", category: "Nationalité" },
        { en: "Spanish", fr: "Espagnol", category: "Nationalité" },
        { en: "Funny", fr: "Drôle", category: "Caractère" },
        { en: "Kind", fr: "Gentil", category: "Caractère" },
        { en: "Brave", fr: "Courageux", category: "Caractère" },
        { en: "Smart", fr: "Intelligent", category: "Caractère" },
        { en: "Tired", fr: "Fatigué", category: "État" },
        { en: "Hungry", fr: "Affamé", category: "État" },
        { en: "Thirsty", fr: "Assoiffé", category: "État" },
        { en: "Clean", fr: "Propre", category: "État" },
        { en: "Dirty", fr: "Sale", category: "État" },
        { en: "Expensive", fr: "Cher", category: "Prix" },
        { en: "Cheap", fr: "Bon marché", category: "Prix" },
        { en: "Empty", fr: "Vide", category: "État" },
        { en: "Full", fr: "Plein", category: "État" },
        { en: "Heavy", fr: "Lourd", category: "Poids" },
        { en: "Light", fr: "Léger", category: "Poids" },
        { en: "New", fr: "Nouveau", category: "Âge" },
        { en: "Interesting", fr: "Intéressant", category: "Qualité" },
        { en: "Boring", fr: "Ennuyeux", category: "Qualité" },
        { en: "Angry", fr: "En colère", category: "Émotion" },
        { en: "Quiet", fr: "Calme", category: "État" }
    ],

    verbs: [
        { base: "Be", preterit: "Was / Were", participle: "Been", fr: "Être", examples: ["I am happy.", "He was here yesterday.", "They have been to London."] },
        { base: "Have", preterit: "Had", participle: "Had", fr: "Avoir", examples: ["I have a car.", "We had lunch.", "She has had a long day."] },
        { base: "Do", preterit: "Did", participle: "Done", fr: "Faire", examples: ["Do your homework.", "He did his best.", "I have done it."] },
        { base: "Say", preterit: "Said", participle: "Said", fr: "Dire", examples: ["Say hello.", "She said goodbye.", "They have said everything."] },
        { base: "Go", preterit: "Went", participle: "Gone", fr: "Aller", examples: ["I go to school.", "He went home.", "They have gone away."] },
        { base: "Get", preterit: "Got", participle: "Got", fr: "Obtenir / Devenir", examples: ["Get a job.", "It got dark.", "I have got a letter."] },
        { base: "Make", preterit: "Made", participle: "Made", fr: "Faire / Fabriquer", examples: ["Make a cake.", "He made a mistake.", "They have made a decision."] },
        { base: "Know", preterit: "Knew", participle: "Known", fr: "Savoir / Connaître", examples: ["I know him.", "She knew the answer.", "I have known her for years."] },
        { base: "Take", preterit: "Took", participle: "Taken", fr: "Prendre", examples: ["Take a bus.", "He took a photo.", "She has taken the key."] },
        { base: "See", preterit: "Saw", participle: "Seen", fr: "Voir", examples: ["I see the sea.", "We saw a movie.", "Have you seen my dog?"] },
        { base: "Come", preterit: "Came", participle: "Come", fr: "Venir", examples: ["Come here.", "He came late.", "They have come back."] },
        { base: "Think", preterit: "Thought", participle: "Thought", fr: "Penser", examples: ["I think so.", "He thought about it.", "I have thought of you."] },
        { base: "Look", preterit: "Looked", participle: "Looked", fr: "Regarder", examples: ["Look at me.", "She looked happy.", "He has looked everywhere."] },
        { base: "Want", preterit: "Wanted", participle: "Wanted", fr: "Vouloir", examples: ["I want an apple.", "They wanted to go.", "He has wanted this for a long time."] },
        { base: "Give", preterit: "Gave", participle: "Given", fr: "Donner", examples: ["Give me a pen.", "He gave her a gift.", "I have given him the book."] },
        { base: "Use", preterit: "Used", participle: "Used", fr: "Utiliser", examples: ["Use your brain.", "He used a computer.", "They have used it before."] },
        { base: "Find", preterit: "Found", participle: "Found", fr: "Trouver", examples: ["Find the key.", "I found a coin.", "He has found a new job."] },
        { base: "Tell", preterit: "Told", participle: "Told", fr: "Dire / Raconter", examples: ["Tell a story.", "He told me a secret.", "I have told you already."] },
        { base: "Ask", preterit: "Asked", participle: "Asked", fr: "Demander", examples: ["Ask a question.", "She asked for help.", "He has asked me three times."] },
        { base: "Work", preterit: "Worked", participle: "Worked", fr: "Travailler", examples: ["I work hard.", "He worked all night.", "She has worked there since 2010."] },
        { base: "Feel", preterit: "Felt", participle: "Felt", fr: "Sentir / Ressentir", examples: ["I feel good.", "She felt tired.", "They have felt better."] },
        { base: "Try", preterit: "Tried", participle: "Tried", fr: "Essayer", examples: ["Try your best.", "He tried to run.", "I have tried that cake."] },
        { base: "Leave", preterit: "Left", participle: "Left", fr: "Partir / Laisser", examples: ["Leave now.", "He left the room.", "She has left her bag."] },
        { base: "Call", preterit: "Called", participle: "Called", fr: "Appeler", examples: ["Call me maybe.", "He called his mom.", "I have called three times."] },
        { base: "Eat", preterit: "Ate", participle: "Eaten", fr: "Manger", examples: ["Eat your pizza.", "He ate a burger.", "She has eaten lunch."] },
        { base: "Drink", preterit: "Drank", participle: "Drunk", fr: "Boire", examples: ["Drink some water.", "He drank a soda.", "They have drunk everything."] },
        { base: "Sleep", preterit: "Slept", participle: "Slept", fr: "Dormir", examples: ["Sleep well.", "She slept all day.", "I haven't slept enough."] },
        { base: "Read", preterit: "Read", participle: "Read", fr: "Lire", examples: ["Read a book.", "He read the news.", "I have read this before."] },
        { base: "Write", preterit: "Wrote", participle: "Written", fr: "Écrire", examples: ["Write a letter.", "She wrote a poem.", "He has written a book."] },
        { base: "Buy", preterit: "Bought", participle: "Bought", fr: "Acheter", examples: ["Buy some milk.", "He bought a car.", "They have bought a house."] },
        // ... (Ajouter d'autres verbes pour arriver à 80 dans la version finale)
        { base: "Run", preterit: "Ran", participle: "Run", fr: "Courir", examples: ["Run fast.", "She ran away.", "I have run a marathon."] },
        { base: "Speak", preterit: "Spoke", participle: "Spoken", fr: "Parler", examples: ["Speak English.", "He spoke to me.", "They have spoken already."] },
        { base: "Understand", preterit: "Understood", participle: "Understood", fr: "Comprendre", examples: ["I understand.", "She understood the lesson.", "He has understood everything."] },
        { base: "Forget", preterit: "Forgot", participle: "Forgotten", fr: "Oublier", examples: ["Don't forget.", "He forgot his keys.", "I have forgotten her name."] },
        { base: "Begin", preterit: "Began", participle: "Begun", fr: "Commencer", examples: ["Begin now.", "It began to rain.", "We have begun the test."] },
        { base: "Break", preterit: "Broke", participle: "Broken", fr: "Casser", examples: ["Don't break it.", "He broke his leg.", "The window is broken."] },
        { base: "Bring", preterit: "Brought", participle: "Brought", fr: "Apporter", examples: ["Bring a coat.", "She brought some food.", "I have brought my laptop."] },
        { base: "Choose", preterit: "Chose", participle: "Chosen", fr: "Choisir", examples: ["Choose a color.", "He chose the red one.", "They have chosen a name."] },
        { base: "Drive", preterit: "Drove", participle: "Driven", fr: "Conduire", examples: ["Drive safe.", "He drove to Paris.", "I have driven a truck."] },
        { base: "Fall", preterit: "Fell", participle: "Fallen", fr: "Tomber", examples: ["Don't fall.", "He fell down.", "The leaves have fallen."] },
        { base: "Keep", preterit: "Kept", participle: "Kept", fr: "Garder", examples: ["Keep calm.", "She kept the secret.", "I have kept my promise."] },
        { base: "Learn", preterit: "Learnt", participle: "Learnt", fr: "Apprendre", examples: ["Learn English.", "He learnt to swim.", "They have learnt a lot."] },
        { base: "Meet", preterit: "Met", participle: "Met", fr: "Rencontrer", examples: ["Meet my friend.", "We met last year.", "I have met him once."] },
        { base: "Pay", preterit: "Paid", participle: "Paid", fr: "Payer", examples: ["Pay the bill.", "He paid by card.", "I have paid for it."] },
        { base: "Send", preterit: "Sent", participle: "Sent", fr: "Envoyer", examples: ["Send an email.", "She sent a letter.", "I have sent the parcel."] },
        { base: "Sing", preterit: "Sang", participle: "Sung", fr: "Chanter", examples: ["Sing a song.", "She sang beautifully.", "He has sung in a choir."] },
        { base: "Sit", preterit: "Sat", participle: "Sat", fr: "S'asseoir", examples: ["Sit down.", "He sat on the chair.", "We have sat here for an hour."] },
        { base: "Stand", preterit: "Stood", participle: "Stood", fr: "Être debout", examples: ["Stand up.", "She stood there.", "I have stood all day."] },
        { base: "Swim", preterit: "Swam", participle: "Swum", fr: "Nager", examples: ["Swim in the sea.", "He swam fast.", "They have swum across."] },
        { base: "Teach", preterit: "Taught", participle: "Taught", fr: "Enseigner", examples: ["Teach me.", "She taught English.", "He has taught for years."] },
        { base: "Wait", preterit: "Waited", participle: "Waited", fr: "Attendre", examples: ["Wait for me.", "He waited an hour.", "She has waited long enough."] },
        { base: "Walk", preterit: "Walked", participle: "Walked", fr: "Marcher", examples: ["Walk the dog.", "We walked home.", "They have walked 5 miles."] },
        { base: "Watch", preterit: "Watched", participle: "Watched", fr: "Regarder", examples: ["Watch TV.", "He watched the game.", "She has watched it twice."] },
        { base: "Open", preterit: "Opened", participle: "Opened", fr: "Ouvrir", examples: ["Open the door.", "He opened a shop.", "The box was opened."] },
        { base: "Close", preterit: "Closed", participle: "Closed", fr: "Fermer", examples: ["Close your eyes.", "She closed the book.", "It is closed."] },
        { base: "Listen", preterit: "Listened", participle: "Listened", fr: "Écouter", examples: ["Listen to music.", "He listened carefully.", "I have listened to you."] },
        { base: "Help", preterit: "Helped", participle: "Helped", fr: "Aider", examples: ["Help me please.", "She helped her mom.", "They have helped us."] },
        { base: "Play", preterit: "Played", participle: "Played", fr: "Jouer", examples: ["Play football.", "He played guitar.", "We have played enough."] },
        { base: "Live", preterit: "Lived", participle: "Lived", fr: "Vivre / Habiter", examples: ["I live in Paris.", "He lived in London.", "She has lived here for 10 years."] },
        { base: "Stop", preterit: "Stopped", participle: "Stopped", fr: "Arrêter", examples: ["Stop now.", "It stopped raining.", "They have stopped."] },
        { base: "Move", preterit: "Moved", participle: "Moved", fr: "Bouger / Déménager", examples: ["Move away.", "They moved house.", "She has moved to NY."] },
        { base: "Become", preterit: "Became", participle: "Become", fr: "Devenir", examples: ["He became a doctor.", "It has become cold.", "She became famous."] },
        { base: "Believe", preterit: "Believed", participle: "Believed", fr: "Croire", examples: ["I believe you.", "She believed in ghosts.", "He has believed me."] },
        { base: "Happen", preterit: "Happened", participle: "Happened", fr: "Arriver / Se passer", examples: ["What happened?", "It happened again.", "Nothing has happened."] },
        { base: "Carry", preterit: "Carried", participle: "Carried", fr: "Porter / Transporter", examples: ["Carry the bag.", "He carried the baby.", "I have carried this."] },
        { base: "Catch", preterit: "Caught", participle: "Caught", fr: "Attraper", examples: ["Catch the ball.", "He caught a cold.", "She has caught the bus."] },
        { base: "Clean", preterit: "Cleaned", participle: "Cleaned", fr: "Nettoyer", examples: ["Clean your room.", "He cleaned the car.", "They have cleaned up."] },
        { base: "Cut", preterit: "Cut", participle: "Cut", fr: "Couper", examples: ["Cut the bread.", "She cut her hair.", "I have cut my finger."] },
        { base: "Dance", preterit: "Danced", participle: "Danced", fr: "Danser", examples: ["Dance with me.", "They danced all night.", "She has danced before."] },
        { base: "Draw", preterit: "Drew", participle: "Drawn", fr: "Dessiner", examples: ["Draw a cat.", "He drew a picture.", "She has drawn a map."] },
        { base: "Dream", preterit: "Dreamt", participle: "Dreamt", fr: "Rêver", examples: ["Dream big.", "He dreamt of flying.", "I have dreamt of this."] },
        { base: "Finish", preterit: "Finished", participle: "Finished", fr: "Finir", examples: ["Finish your meal.", "She finished her work.", "It is finished."] },
        { base: "Fly", preterit: "Flew", participle: "Flown", fr: "Voler (avion/oiseau)", examples: ["Birds fly.", "He flew to Tokyo.", "I have flown twice."] },
        { base: "Grow", preterit: "Grew", participle: "Grown", fr: "Grandir / Pousser", examples: ["Plants grow.", "He grew up fast.", "She has grown tall."] },
        { base: "Hear", preterit: "Heard", participle: "Heard", fr: "Entendre", examples: ["Hear the noise.", "She heard a sound.", "I have heard that."] },
        { base: "Hold", preterit: "Held", participle: "Held", fr: "Tenir", examples: ["Hold my hand.", "He held the trophy.", "She has held it."] },
        { base: "Jump", preterit: "Jumped", participle: "Jumped", fr: "Sauter", examples: ["Jump high.", "He jumped the fence.", "They have jumped."] },
        { base: "Kill", preterit: "Killed", participle: "Killed", fr: "Tuer", examples: ["Don't kill it.", "He killed the spider.", "Time was killed."] },
        { base: "Laugh", preterit: "Laughed", participle: "Laughed", fr: "Rire", examples: ["Laugh out loud.", "She laughed at me.", "They have laughed."] },
        { base: "Lose", preterit: "Lost", participle: "Lost", fr: "Perdre", examples: ["Don't lose hope.", "He lost his wallet.", "They have lost."] }
    ],

    prepositions: [
        { en: "In", fr: "Dans", type: "Lieu", example: "In the box.", translation: "Dans la boîte." },
        { en: "On", fr: "Sur", type: "Lieu", example: "On the table.", translation: "Sur la table." },
        { en: "Under", fr: "Sous", type: "Lieu", example: "Under the bed.", translation: "Sous le lit." },
        { en: "Behind", fr: "Derrière", type: "Lieu", example: "Behind the door.", translation: "Derrière la porte." },
        { en: "In front of", fr: "Devant", type: "Lieu", example: "In front of the TV.", translation: "Devant la télé." },
        { en: "Next to", fr: "À côté de", type: "Lieu", example: "Next to the car.", translation: "À côté de la voiture." },
        { en: "Between", fr: "Entre", type: "Lieu", example: "Between two trees.", translation: "Entre deux arbres." },
        { en: "At", fr: "À", type: "Temps", example: "At 5 o'clock.", translation: "À 5 heures." },
        { en: "On", fr: "Le (jour)", type: "Temps", example: "On Monday.", translation: "Lundi." },
        { en: "In", fr: "En / Au", type: "Temps", example: "In summer.", translation: "En été." }
    ],

    translations: [
        { fr: "Je suis un garçon.", en: "I am a boy.", level: 1 },
        { fr: "Elle a un chat rouge.", en: "She has a red cat.", level: 1 },
        { fr: "Ils jouent au football.", en: "They are playing football.", level: 1 },
        { fr: "Où est mon sac ?", en: "Where is my bag?", level: 1 },
        { fr: "Le livre est sur la table.", en: "The book is on the table.", level: 1 },
        { fr: "J'aime les pommes.", en: "I like apples.", level: 1 },
        { fr: "Il est très grand.", en: "He is very tall.", level: 1 },
        { fr: "Nous allons à l'école.", en: "We are going to school.", level: 2 },
        { fr: "Elle ne mange pas de viande.", en: "She doesn't eat meat.", level: 2 },
        { fr: "Est-ce que tu parles anglais ?", en: "Do you speak English?", level: 2 },
        { fr: "Mon frère a dix ans.", en: "My brother is ten years old.", level: 2 },
        { fr: "Il fait froid aujourd'hui.", en: "It is cold today.", level: 2 },
        { fr: "J'ai vu un film hier.", en: "I saw a movie yesterday.", level: 3 },
        { fr: "Elle habitait à Londres.", en: "She lived in London.", level: 3 },
        { fr: "Qu'est-ce que tu as fait ?", en: "What did you do?", level: 3 },
        { fr: "Le gâteau a été mangé par le chien.", en: "The cake was eaten by the dog.", level: 4 },
        { fr: "Une nouvelle maison sera construite.", en: "A new house will be built.", level: 4 },
        { fr: "Je peux t'aider ?", en: "Can I help you?", level: 2 },
        { fr: "Tu devrais étudier davantage.", en: "You should study more.", level: 3 },
        { fr: "Il doit pleuvoir demain.", en: "It might rain tomorrow.", level: 3 },
        { fr: "J'ai fini mes devoirs.", en: "I have finished my homework.", level: 3 },
        { fr: "Elle est plus petite que son frère.", en: "She is shorter than her brother.", level: 3 },
        { fr: "C'est la plus belle fleur du jardin.", en: "It is the most beautiful flower in the garden.", level: 3 },
        { fr: "Il y a un chat sous la voiture.", en: "There is a cat under the car.", level: 2 },
        { fr: "Il n'y a pas de lait dans le frigo.", en: "There is no milk in the fridge.", level: 2 },
        { fr: "Est-ce qu'il y a des oeufs ?", en: "Are there any eggs?", level: 2 },
        { fr: "Je vais regarder la télé.", en: "I am going to watch TV.", level: 2 },
        { fr: "Qu'est-ce que tu vas manger ?", en: "What are you going to eat?", level: 2 },
        { fr: "Je ne l'ai jamais vu.", en: "I have never seen him.", level: 3 },
        { fr: "Depuis quand es-tu ici ?", en: "How long have you been here?", level: 3 },
        { fr: "Je suis ici depuis deux heures.", en: "I have been here for two hours.", level: 3 },
        { fr: "Il fait beau aujourd'hui, n'est-ce pas ?", en: "It's a nice day today, isn't it?", level: 3 },
        { fr: "Elle ne peut pas venir.", en: "She cannot come.", level: 2 },
        { fr: "Ils étaient en train de dormir.", en: "They were sleeping.", level: 3 },
        { fr: "Pendant que je lisais, le téléphone a sonné.", en: "While I was reading, the phone rang.", level: 4 },
        { fr: "La porte est fermée.", en: "The door is closed.", level: 2 },
        { fr: "Les fenêtres sont ouvertes.", en: "The windows are open.", level: 2 },
        { fr: "C'est à qui ?", en: "Whose is this?", level: 2 },
        { fr: "C'est le mien.", en: "It is mine.", level: 2 },
        { fr: "Où habitent-ils ?", en: "Where do they live?", level: 1 },
        { fr: "Comment vas-tu ?", en: "How are you?", level: 1 },
        { fr: "Quel âge as-tu ?", en: "How old are you?", level: 1 },
        { fr: "Quelle heure est-il ?", en: "What time is it?", level: 2 },
        { fr: "Je me lève à sept heures.", en: "I get up at seven o'clock.", level: 2 },
        { fr: "Il prend sa douche tous les matins.", en: "He takes a shower every morning.", level: 2 },
        { fr: "Nous ne travaillons pas le dimanche.", en: "We don't work on Sundays.", level: 2 },
        { fr: "Regarde cet oiseau !", en: "Look at that bird!", level: 1 },
        { fr: "Écoute-moi s'il te plaît.", en: "Listen to me please.", level: 1 },
        { fr: "Ne cours pas dans le couloir.", en: "Don't run in the corridor.", level: 2 },
        { fr: "C'est mon livre préféré.", en: "It is my favourite book.", level: 2 },
        { fr: "Elle est très intelligente.", en: "She is very smart.", level: 2 },
        { fr: "Ils sont très gentils.", en: "They are very kind.", level: 2 },
        { fr: "Il y a beaucoup de monde.", en: "There are a lot of people.", level: 2 },
        { fr: "Il n'y a pas assez d'eau.", en: "There is not enough water.", level: 3 },
        { fr: "J'ai trop de travail.", en: "I have too much work.", level: 3 },
        { fr: "Est-ce que je peux ouvrir la fenêtre ?", en: "May I open the window?", level: 2 },
        { fr: "Tu ne dois pas fumer ici.", en: "You must not smoke here.", level: 3 },
        { fr: "Il faut que nous partions.", en: "We must leave.", level: 3 }
    ]
};
